author: PA_Exception
name: NCSWS
version: 1.0
main: io.github.paexception.mcsws.plugin.MCSWS
commands:
  wakeup:
    description: Manage who can wakeup the server
    usage: "/wakeup <add|rm> <name> || /wakeup list"
    aliases: [ wu, wup ]
